import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { lint, meta, parse, roadmap, stripComments } from '../bin/lib/backlog.mjs'
import { normalise } from '../bin/lib/config.mjs'

const fixture = (f) => readFileSync(new URL(`./fixtures/${f}`, import.meta.url), 'utf8')
const cfg = normalise(JSON.parse(fixture('config.json')))
const model = parse(fixture('backlog.md'), cfg)

test('the fixture parses and lints clean', () => {
  assert.deepEqual(model.errors, [])
  assert.deepEqual(lint(model, cfg), [])
  assert.deepEqual(model.milestones.map((m) => [m.title, m.version, m.phase, m.items.length]), [
    ['v0.1.0 — First light', 'v0.1.0', 'now', 4],
    ['v0.2.0 — Second light', 'v0.2.0', 'next', 3],
  ])
  assert.deepEqual(model.items.map((i) => i.id), ['DM-1', 'DM-2', 'DM-3', 'DM-4', 'DM-5', 'DM-6', 'DM-7'])
})

test('a fenced block is skipped whole, headings and items alike', () => {
  assert.ok(!model.items.some((i) => i.id === 'DM-99'))
  assert.ok(!model.milestones.some((m) => m.version === 'v9.9.0'))
})

test('continuation lines join the body; the meta comment leaves it', () => {
  const it = model.items.find((i) => i.id === 'DM-3')
  assert.equal(it.body, 'the sync creates it, with a body that spans two lines and an `inline` code span.')
  assert.deepEqual(it.meta, { prio: 'med', size: 'M', labels: 'core,docs' })
  assert.equal(it.status, 'open')
  assert.equal(model.items[0].status, 'shipped')
  assert.equal(model.items[0].meta.ver, '0.1.0')
})

test('meta keeps an "=" inside a value and returns null without the comment', () => {
  assert.deepEqual(meta('x <!-- dm: a=b=c d= -->', 'dm'), { a: 'b=c', d: '' })
  assert.equal(meta('no comment', 'dm'), null)
  assert.equal(meta('<!-- other: a=b -->', 'dm'), null)
})

test('no HTML comment survives into a body, terminated or not', () => {
  assert.equal(stripComments('a <!-- x --> b <!-- y'), 'a  b')
  // One pass would leave `<!-- y -->` behind: removing the inner comment forms a new one.
  assert.equal(stripComments('<!<!-- x -->-- y -->z'), 'z')
})

test('the roadmap is the committed layout, byte for byte', () => {
  assert.equal(roadmap(model, cfg), fixture('roadmap.expected.md'))
})

test('the roadmap names the configured regenerate command, and the comment drops its runner', () => {
  const old = normalise({ prefix: 'DM', name: 'demo', regenerate: 'node scripts/backlog.mjs roadmap' })
  const out = roadmap(model, old)
  assert.match(out, /<!-- GENERATED by scripts\/backlog\.mjs roadmap — do not edit by hand\. -->/)
  assert.match(out, /Regenerate it with `node scripts\/backlog\.mjs roadmap` after/)
})

const bad = (text, c = cfg) => lint(parse(text, c), c)
const has = (errs, needle) => assert.ok(errs.some((e) => e.includes(needle)), `expected "${needle}" in:\n${errs.join('\n')}`)

test('lint catches every fault the replaced scripts caught', () => {
  const errs = bad(
    [
      '## v1.0.0 — X <!-- ms: phase=now -->',
      '',
      '- [ ] **DM-1 — a**: b. <!-- dm: prio=high size=S labels=core ver=1.0.0 -->',
      '- [ ] **DM-1 — c**: d.',
      '- [x] **DM-2 — e**: f. <!-- dm: prio=zzz size=XXL labels=nope -->',
      '- [ ] **DM-3 — g**: <!-- dm: prio=low size=S labels= -->',
      '- [ ] **DM-x — h**: i. <!-- dm: prio=low size=S labels=core -->',
      '',
    ].join('\n'),
  )
  for (const needle of ['already used on line 3', 'no <!-- dm:', 'carries ver=1.0.0', 'prio must be', 'size must be', 'unknown label "nope"', 'shipped but has no ver=', 'at least one label', 'DM-3 has no body', 'item does not match'])
    has(errs, needle)
  for (const e of errs) assert.match(e, /^BACKLOG\.md:\d+: /)
})

test('lint catches milestone faults', () => {
  const errs = bad(['## Not versioned <!-- ms: phase=now -->', '## v1.0.0 — A <!-- ms: phase=soon -->', '## v1.0.0 — A <!-- ms: phase=now -->', ''].join('\n'))
  has(errs, 'must start with a version')
  has(errs, 'phase must be one of now|next|later|shipped, got "soon"')
  has(errs, 'already a heading on line 2')
})

test('an item outside a milestone, or under a plain heading, is an error', () => {
  const errs = bad(['- [ ] **DM-1 — a**: b. <!-- dm: prio=high size=S labels=core -->', '## Notes', '- [ ] **DM-2 — c**: d. <!-- dm: prio=high size=S labels=core -->', ''].join('\n'))
  has(errs, 'DM-1 is not under a milestone heading')
  has(errs, 'DM-2 is not under a milestone heading')
})

test('a prio- label is refused: it comes from prio=', () => {
  has(bad('## v1.0.0 — A <!-- ms: phase=now -->\n- [ ] **DM-1 — a**: b. <!-- dm: prio=high size=S labels=core,prio-high -->\n'), 'is added from prio=')
})

test('an item under another prefix, or ticked with [X], does not vanish silently', () => {
  const errs = bad('## v1.0.0 — A <!-- ms: phase=now -->\n- [ ] **ZZ-1 — a**: b.\n- [X] **DM-2 — a**: b.\n')
  has(errs, 'item id prefix "ZZ" is not the configured "DM"')
  has(errs, 'use a lower-case [x]')
})

test('with no labels configured any label passes', () => {
  const open = normalise({ prefix: 'DM' })
  assert.deepEqual(bad('## v1.0.0 — A <!-- ms: phase=now -->\n- [ ] **DM-1 — a**: b. <!-- dm: prio=high size=S labels=whatever -->\n', open), [])
})

test('the meta key and the file name are configurable', () => {
  const c = normalise({ prefix: 'HLD', meta: 'doc', backlog: 'docs/PLAN.md' })
  const m = parse('## v1.0.0 — A <!-- ms: phase=now -->\n- [ ] **HLD-1 — a**: b. <!-- doc: prio=high size=S labels=x -->\n', c)
  assert.deepEqual(lint(m, c), [])
  assert.equal(m.items[0].meta.prio, 'high')
  const errs = bad('## v1.0.0 — A <!-- ms: phase=now -->\n- [ ] **HLD-1 — a**: b. <!-- hld: prio=high size=S labels=x -->\n', c)
  has(errs, 'docs/PLAN.md:2: HLD-1 has no <!-- doc: ... --> metadata')
  assert.match(roadmap(m, c), /from \[docs\/PLAN\.md\]\(docs\/PLAN\.md\)/)
})
